import Image from "next/image";
import { Inter } from "next/font/google";

import Hero from "../../assets/hero.jpg";

import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ptBR">
      <body className={inter.className}>
        <div className="flex min-h-screen justify-between">
          <main className="bg-zinc-900 text-white max-w-xl w-full rounded-r-2xl flex flex-col justify-center px-20">
            {children}
          </main>
          <aside className="flex flex-col flex-1 justify-center items-center">
            <Image src={Hero} alt="" width={500} />
            <h1 className="text-3xl font-bold">Seja muito bem-vindo!</h1>
            <p className="text-xl">Veio procurar emprego ou um estágio?</p>
            <p className="text-xl">Vamos te ajudar =)</p>
          </aside>
        </div>
      </body>
    </html>
  );
}
